const { ipcRenderer } = require('electron');
let currentState=null, giftRules={version:2,mode:'game-actions-only',rules:{}}, learned={}, rankings={users:{}}, liveWindowOpened=false;
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for(const b of document.querySelectorAll('.nav')) b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');$('pageTitle').textContent=b.textContent;if(b.dataset.tab==='ranking')loadRanking();if(b.dataset.tab==='gifts')loadGifts();};
function renderRank(el,rows=[]){$(el).innerHTML=rows.slice(0,10).map((r,i)=>`<div class="rankRow"><b>#${i+1}</b><span>${esc(r.displayName||r.uniqueId||'viewer')}</span><b>${Number(r.score||0).toLocaleString()}</b></div>`).join('')||'<div class="muted">Chưa có dữ liệu</div>';}
function setCore(id,on){$(id).textContent=on?'ON':'OFF';$(id).style.color=on?'#5fe28b':'#ff6f7b';}
function renderState(s){currentState=s;if(!s)return;const p=s.ppsspp||{},ses=s.session||{},core=s.combatCore||{};$('ppStatus').textContent=p.connected?'CONNECTED':'OFF';$('ppDot').className='dot '+(p.connected?'on':'bad');$('liveStatus').textContent=liveWindowOpened?'OPEN':'OFF';$('liveDot').className='dot '+(liveWindowOpened?'on':'');$('gamePhase').textContent=p.gamePhase||'-';$('patchMini').textContent=p.patchesApplied?'ON':'OFF';$('p1hp').textContent=p.p1HP??'-';$('p2hp').textContent=p.p2HP??'-';$('rounds').textContent=ses.rounds||0;$('members').textContent=ses.memberCount||0;$('modeAddr').textContent=p.mode||'-';$('stateAddr').textContent=p.state||'-';$('patchState').textContent=p.patchesApplied?'ON':'OFF';setCore('coreAnti',core.antiHeal!==false);setCore('coreKO',core.realKO!==false);setCore('coreOutro',core.outro!==false);setCore('corePick',core.winnerPick!==false);setCore('coreCS',core.fullCharacterSelect!==false);setCore('coreRandom',core.p2Random30!==false);renderRank('topP1',ses.leaderboardP1);renderRank('topP2',ses.leaderboardP2);const a=ses.activePick;$('pickState').textContent=a?`${a.winnerTeam} thắng | Top1 ${a.top1Name} | ${a.status} | pick=${a.pick||'-'}`:'Chưa có winner pick.';if(Array.isArray(s.logs))$('logs').textContent=s.logs.slice(-80).map(x=>`[${new Date(x.at).toLocaleTimeString()}] ${x.message}`).join('\n');}
ipcRenderer.on('controller-state',(_,s)=>renderState(s));ipcRenderer.on('app-log',(_,x)=>{$('logs').textContent+=`\n[APP] ${x.message}`});ipcRenderer.on('live-event',(_,e)=>{$('lastEvent').textContent=JSON.stringify(e,null,2)});ipcRenderer.on('scoring-event',(_,e)=>{$('lastScoring').textContent=JSON.stringify(e,null,2);loadGifts()});
async function init(){const s=await ipcRenderer.invoke('get-settings');$('liveUsername').value=s.liveUsername||'';$('isoPath').value=s.isoPath||'';$('debuggerUrl').value=s.ppssppDebugger||'ws://127.0.0.1:9000/debugger';$('showOverlay').checked=s.showOverlay!==false;giftRules=await ipcRenderer.invoke('get-rules');learned=await ipcRenderer.invoke('get-learned-gifts');const eng=await ipcRenderer.invoke('get-engine-info');$('engineInfo').textContent=eng.bundledExists?`NATIVE FLOGB ENGINE: ${eng.bundledPath}`:`NATIVE ENGINE MISSING: bản build này không hợp lệ, hãy build lại bằng workflow Native Unified.`;renderGiftTable();}
$('btnOpenLive').onclick=async()=>{try{await ipcRenderer.invoke('open-live',$('liveUsername').value);liveWindowOpened=true}catch(e){alert(e.message)}};$('btnOverlay').onclick=()=>ipcRenderer.invoke('toggle-overlay');$('btnReset').onclick=async()=>{if(confirm('Reset đội, BXH phiên và winner pick?'))await ipcRenderer.invoke('reset-session');};$('chooseISO').onclick=async()=>{$('isoPath').value=await ipcRenderer.invoke('choose-file',[{name:'PSP Game',extensions:['iso','cso','chd']}])};
async function saveSettings(){const cur=await ipcRenderer.invoke('get-settings');return ipcRenderer.invoke('save-settings',{...cur,liveUsername:$('liveUsername').value,isoPath:$('isoPath').value,ppssppDebugger:$('debuggerUrl').value,showOverlay:$('showOverlay').checked});}
$('launchPP').onclick=async()=>{try{await saveSettings();await ipcRenderer.invoke('launch-ppsspp')}catch(e){alert('Không thể khởi chạy FloGB Engine: '+(e?.message||e))}};$('saveSettings').onclick=async()=>{await saveSettings();alert('Đã lưu cài đặt.')};
function norm(s){return String(s||'').trim().toLowerCase();}
function configuredRule(g){return giftRules.rules?.[String(g.giftId)]||Object.values(giftRules.rules||{}).find(r=>norm(r.name)===norm(g.name))||null;}
function giftRows(){const q=norm($('giftSearch')?.value),f=$('giftFilter')?.value||'all';const ids=new Set([...Object.keys(learned||{}),...Object.keys(giftRules.rules||{}).filter(k=>!k.startsWith('name:'))]);const rows=[];for(const id of ids){const l=learned[id]||{},r=giftRules.rules?.[id]||{};const g={giftId:id,name:l.name||r.name||id,diamondCount:l.diamondCount||0,seenCount:l.seenCount||0,lastSender:l.lastSender||'',configured:!!giftRules.rules?.[id]};if(q&&!norm(g.name+' '+g.giftId).includes(q))continue;if(f==='configured'&&!g.configured)continue;if(f==='unconfigured'&&g.configured)continue;rows.push(g);}return rows.sort((a,b)=>(b.seenCount-a.seenCount)||a.name.localeCompare(b.name));}
function renderGiftTable(){if(!$('giftBody'))return;const rows=giftRows();$('giftBody').innerHTML=rows.map(g=>{const r=configuredRule(g);if(!r)return `<tr data-id="${esc(g.giftId)}"><td><b>${esc(g.name)}</b><div class="giftMeta">Người gửi gần nhất: ${esc(g.lastSender||'-')}</div></td><td>${esc(g.giftId)}</td><td>${g.seenCount||0}</td><td><b class="warn">CHƯA ADD</b></td><td colspan="4" class="muted">Không tác động game</td><td><button class="btnSmall addRule">+ ADD RULE</button></td></tr>`;const a=Array.isArray(r.actions)&&r.actions[0]?r.actions[0]:{type:r.action||'input',amount:r.amount||1,button:r.button||'cross'};return `<tr data-id="${esc(g.giftId)}" class="${r.enabled===false?'ruleOff':''}"><td><b>${esc(g.name)}</b><div class="giftMeta">${esc(g.lastSender||'')}</div></td><td>${esc(g.giftId)}</td><td>${g.seenCount||0}</td><td><b>ĐÃ ADD</b></td><td><select class="cellSelect action"><option value="input" ${a.type==='input'?'selected':''}>Bấm nút PSP</option><option value="heal_team" ${a.type==='heal_team'?'selected':''}>Hồi HP team gửi</option><option value="damage_enemy" ${a.type==='damage_enemy'?'selected':''}>Trừ HP đối thủ</option><option value="winner_p1" ${a.type==='winner_p1'?'selected':''}>Trigger Winner P1</option><option value="winner_p2" ${a.type==='winner_p2'?'selected':''}>Trigger Winner P2</option><option value="video" ${a.type==='video'?'selected':''}>Video/Effect</option></select></td><td><input class="cellInput amount" type="number" value="${Number(a.amount||1)}"></td><td><input class="cellInput button" value="${esc(a.button||'cross')}" title="cross/start/up/down/left/right"></td><td><input class="enabled" type="checkbox" ${r.enabled===false?'':'checked'}></td><td><button class="btnSmall removeRule danger">Xóa Rule</button></td></tr>`}).join('')||'<tr><td colspan="9" class="muted">Chưa thấy gift thật nào. Mở LIVE, khi có gift nó sẽ tự xuất hiện ở đây.</td></tr>';document.querySelectorAll('.addRule').forEach(b=>b.onclick=()=>{const tr=b.closest('tr'),id=tr.dataset.id,l=learned[id]||{};giftRules.rules=giftRules.rules||{};giftRules.rules[id]={name:l.name||id,enabled:true,actions:[{type:'input',button:'cross',amount:1}]};renderGiftTable();});document.querySelectorAll('.removeRule').forEach(b=>b.onclick=()=>{const id=b.closest('tr').dataset.id;delete giftRules.rules[id];renderGiftTable();});}
$('giftSearch').oninput=renderGiftTable;$('giftFilter').onchange=renderGiftTable;$('btnSaveRules').onclick=async()=>{for(const tr of document.querySelectorAll('#giftBody tr[data-id]')){const id=tr.dataset.id,r=giftRules.rules?.[id];if(!r)continue;const action=tr.querySelector('.action');if(!action)continue;r.enabled=tr.querySelector('.enabled').checked;r.actions=[{type:action.value,amount:Number(tr.querySelector('.amount').value)||0,button:tr.querySelector('.button').value||'cross',hpCap:250}];}giftRules=await ipcRenderer.invoke('save-rules',giftRules);alert('Đã lưu Game Rule. Không cần build lại EXE.');};
async function loadGifts(){giftRules=await ipcRenderer.invoke('get-rules');learned=await ipcRenderer.invoke('get-learned-gifts');renderGiftTable();}
function periodScore(u,mode){if(mode==='all')return Number(u.total||0);const n=new Date(),cut=new Date(n);cut.setHours(0,0,0,0);cut.setDate(cut.getDate()-(mode==='week'?6:29));let v=0;for(const [d,x] of Object.entries(u.daily||{}))if(new Date(d)>=cut)v+=Number(x||0);return v;}
async function loadRanking(){rankings=await ipcRenderer.invoke('get-rankings');const mode=$('rankMode').value;const rows=Object.values(rankings.users||{}).map(u=>({...u,score:periodScore(u,mode)})).sort((a,b)=>b.score-a.score).slice(0,100);$('rank100').innerHTML=rows.map((u,i)=>`<div class="r"><b>#${i+1}</b><span>${u.avatar?`<img src="${esc(u.avatar)}">`:''} ${esc(u.uniqueId||u.nickname||u.id)}</span><b>${u.score.toLocaleString()}</b><span>${u.gifts||0} quà</span></div>`).join('')||'<div class="muted">Chưa có dữ liệu.</div>';}
$('rankMode').onchange=loadRanking;window.manualWinner=t=>ipcRenderer.invoke('manual-winner',t).catch(e=>alert(e.message));init();
